# tests/harness/codex/wiring.sh
wiring() {
  local r="$HARNESS_REPO_ROOT"
  # Root AGENTS.md is Codex's zero-install steering (pi-codex keystone).
  if [ -f "$r/AGENTS.md" ]; then
    file-contains "$r/AGENTS.md" 'GENERATED by tools/gather.py'
    file-contains "$r/AGENTS.md" '\.agents/AGENTS\.md'
  else
    skip "root AGENTS.md absent (pi-codex keystone not on this branch yet)"
  fi
  # Codex plugin manifest — only once hub-spoke WI-5 emits it.
  if [ -f "$r/.codex-plugin/plugin.json" ]; then
    cmd-succeeds "codex plugin.json is valid JSON" -- python3 -c "import json,sys; json.load(open('$r/.codex-plugin/plugin.json'))"
    file-contains "$r/.codex-plugin/plugin.json" '"hooks"[[:space:]]*:[[:space:]]*\{\}'
  else
    skip ".codex-plugin/plugin.json absent (hub-spoke WI-5 not landed)"
  fi
}
