# tests/harness/codex/wiring.sh
wiring() {
  local r="$HARNESS_REPO_ROOT"

  # Root AGENTS.md is Codex's zero-install steering (pi-codex keystone).
  file-contains "$r/AGENTS.md" 'GENERATED by tools/gather.py'
  file-contains "$r/AGENTS.md" '\.agents/AGENTS\.md'

  # Codex plugin manifest — emitted into dist/ by gather. dist/ published as a git
  # repo IS the Codex marketplace, so the plugin sits at its root.
  local m="$r/dist/.codex-plugin/plugin.json"
  cmd-succeeds "codex plugin.json is valid JSON" -- python3 -c "import json; json.load(open('$m'))"
  file-contains "$m" '"hooks"[[:space:]]*:[[:space:]]*\{\}'
  file-contains "$m" '"skills"[[:space:]]*:[[:space:]]*"\./agent-skills/"'

  # Marketplace manifest.
  local mk="$r/dist/.agents/plugins/marketplace.json"
  cmd-succeeds "codex marketplace.json is valid JSON" -- python3 -c "import json; json.load(open('$mk'))"
  file-contains "$mk" '"name"[[:space:]]*:[[:space:]]*"awow"'

  # Commands-as-skills surface — every command AND skill rendered as <name>/SKILL.md.
  file-exists "$r/dist/agent-skills/setup-awow/SKILL.md"
  file-exists "$r/dist/agent-skills/daily-digest/SKILL.md"

  # Version lockstep: the codex manifest is derived from the one canonical plugin
  # manifest, so it cannot ship a stale version.
  cmd-succeeds "codex manifest version == canonical plugin version" -- python3 -c "
import json
a = json.load(open('$r/.claude-plugin/plugin.json'))['version']
b = json.load(open('$m'))['version']
raise SystemExit(0 if a == b else 1)"
}
