"""Sync .agents/ → .claude/ + .github/ as pointer stubs.

.agents/ is the single source of truth. This script generates tiny pointer
stubs in the harness folders that redirect the agent to the canonical source.
No substantive content is copied — only the frontmatter (name, description)
the harness needs for discovery, plus a one-line body telling the agent to
read the real file under .agents/.

Why pointers (not copies, not symlinks):
- Copies drift the moment someone forgets to re-run gather.
- Symlinks are fragile across platforms and cannot carry harness-specific
  frontmatter.
- Pointers contain no substantive content, so there is nothing to drift.
  The only thing gather syncs is discovery metadata.

Layout produced
---------------
    .agents/CLAUDE.md                    → .claude/CLAUDE.md
                                         → .github/copilot-instructions.md
                                         → .github/AGENTS.md
    .agents/commands/<phase>/<name>.md   → .claude/commands/<name>.md
                                         → .github/prompts/<name>.prompt.md
    .agents/commands/<name>.md (top)     → same as above (phase folder flat-
                                            tens; meta commands also flat)

The `.prompt.md` extension under .github/prompts/ is required: VS Code's
GitHub Copilot Chat discovers prompt files by that exact suffix; plain `.md`
is silently ignored.
    .agents/skills/<name>/SKILL.md       → .claude/skills/<name>/SKILL.md
                                         → .github/skills/<name>/SKILL.md
    .agents/skills/<name>.md             → .claude/skills/<name>/SKILL.md
                                         → .github/skills/<name>/SKILL.md
                                            (declarative skills are wrapped
                                            in a synthesised SKILL.md stub
                                            so the harness discovers them)

Files named README.md and any path under `_archetypes/` are not mirrored;
they are documentation, not commands.

Usage
-----
    python tools/gather.py                  # write all stubs
    python tools/gather.py --check          # exit 1 if any stub is out of date
    python tools/gather.py --surface claude # only emit to .claude/
    python tools/gather.py --surface github # only emit to .github/

Orphans
-------
Stubs whose source has been removed are reported (and removed in non-check
mode) only if they carry the GENERATED header this script writes, so user-
added files are never deleted.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / ".agents"
CLAUDE_DIR = REPO_ROOT / ".claude"
GITHUB_DIR = REPO_ROOT / ".github"

SKIP_FILENAMES = {"README.md"}
SKIP_DIR_PARTS = {"_archetypes"}
GENERATED_MARKER = "<!-- GENERATED by tools/gather.py"


@dataclass(frozen=True)
class Stub:
    target: Path
    content: str


# ---------- minimal frontmatter parser ----------

_FM_DELIM = "---\n"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (scalar fields, body). Lists and block scalars are ignored — we
    only need top-level strings like name, description, removes_pain."""
    if not text.startswith(_FM_DELIM):
        return {}, text
    end = text.find("\n" + _FM_DELIM, len(_FM_DELIM))
    if end == -1:
        return {}, text
    fm_block = text[len(_FM_DELIM):end]
    body = text[end + len("\n" + _FM_DELIM):]
    fields: dict[str, str] = {}
    for line in fm_block.splitlines():
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$', line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if raw == "" or raw.startswith("[") or raw.startswith("{"):
            continue
        if (raw.startswith('"') and raw.endswith('"')) or (
            raw.startswith("'") and raw.endswith("'")
        ):
            raw = raw[1:-1]
        fields[key] = raw
    return fields, body


def first_h1(body: str) -> str | None:
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return None


# ---------- relative path helpers ----------


def rel_link(stub_target: Path, source: Path) -> str:
    """Markdown-link path from a stub file to its source under .agents/."""
    rel = Path("../" * (len(stub_target.relative_to(REPO_ROOT).parts) - 1)) / source.relative_to(REPO_ROOT)
    return str(rel)


# ---------- stub generators ----------


def header(source: Path) -> str:
    rel = source.relative_to(REPO_ROOT)
    return f"{GENERATED_MARKER} — DO NOT EDIT. Source: {rel} -->"


def command_description(fields: dict[str, str], body: str) -> str:
    """Best-effort one-liner description for a command stub.

    Priority: explicit `description` field → H1 after the em-dash → H1 → empty.
    """
    if "description" in fields:
        return fields["description"]
    h1 = first_h1(body)
    if h1:
        if "—" in h1:
            return h1.split("—", 1)[1].strip()
        if " - " in h1:
            return h1.split(" - ", 1)[1].strip()
        return h1
    return ""


def gen_command_stub(source: Path, stub_target: Path) -> str:
    text = source.read_text()
    fields, body = parse_frontmatter(text)
    desc = command_description(fields, body)
    link = rel_link(stub_target, source)
    fm_lines = ["---"]
    if desc:
        # YAML-quote (double, with internal quote escape)
        fm_lines.append(f'description: "{desc.replace(chr(34), chr(92) + chr(34))}"')
    fm_lines.append("---")
    fm = "\n".join(fm_lines)
    return (
        f"{fm}\n\n"
        f"{header(source)}\n\n"
        f"Execute the command defined at [`{source.relative_to(REPO_ROOT)}`]({link}). "
        f"Read that file and follow its instructions, applying any arguments the user provided "
        f"to this invocation. The body of this stub carries no substantive content — the real "
        f"prompt lives at the path above.\n\n"
        f"Edits must be made in `{source.relative_to(REPO_ROOT)}` and re-mirrored with "
        f"`python tools/gather.py`.\n"
    )


def gen_skill_stub(source: Path, stub_target: Path, name: str, description: str) -> str:
    link = rel_link(stub_target, source)
    desc_escaped = description.replace(chr(34), chr(92) + chr(34))
    scripts_hint = ""
    if source.name == "SKILL.md" and (source.parent / "scripts").is_dir():
        scripts_rel = (source.parent / "scripts").relative_to(REPO_ROOT)
        scripts_hint = (
            f"\nScripts bundled with this skill live at `{scripts_rel}/` and should be invoked "
            f"from the repo root.\n"
        )
    return (
        f"---\n"
        f"name: {name}\n"
        f'description: "{desc_escaped}"\n'
        f"---\n\n"
        f"{header(source)}\n\n"
        f"# {name}\n\n"
        f"This skill's full rubric lives at [`{source.relative_to(REPO_ROOT)}`]({link}). "
        f"Read that file before acting on this skill. The body of this stub carries no "
        f"substantive content.\n"
        f"{scripts_hint}\n"
        f"Edits must be made in `{source.relative_to(REPO_ROOT)}` and re-mirrored with "
        f"`python tools/gather.py`.\n"
    )


def gen_top_level_instructions(stub_target: Path, harness_label: str) -> str:
    source = AGENTS_DIR / "CLAUDE.md"
    link = rel_link(stub_target, source)
    return (
        f"{header(source)}\n\n"
        f"# Agent instructions ({harness_label})\n\n"
        f"This repo uses a single source of truth for agent instructions, commands, and skills: "
        f"the `.agents/` directory. **Before doing anything else, read "
        f"[`.agents/CLAUDE.md`]({link}) and follow its instructions.** That file is the canonical "
        f"rule set for both Claude Code and GitHub Copilot working in this repo.\n\n"
        f"- Commands → `.agents/commands/` (also discoverable from this surface as pointer stubs)\n"
        f"- Skills → `.agents/skills/` (also discoverable from this surface as pointer stubs)\n"
        f"- Conventions and context → `context/`\n\n"
        f"Files in this folder are auto-generated pointer stubs produced by `tools/gather.py`. "
        f"They exist only so the harness can discover commands and skills natively; the "
        f"substantive content lives under `.agents/`. Edits made here are overwritten on the "
        f"next gather.\n"
    )


def gen_folder_readme(stub_target: Path, source_dir: Path, harness_label: str) -> str:
    link = rel_link(stub_target, source_dir)
    return (
        f"{header(source_dir)}\n\n"
        f"# {stub_target.parent.name}/ — auto-generated pointer stubs\n\n"
        f"Files here are pointer stubs produced by `tools/gather.py`. Each one carries the "
        f"frontmatter the {harness_label} harness needs for discovery plus a one-line body "
        f"pointing to the canonical source under [`{source_dir.relative_to(REPO_ROOT)}/`]({link}).\n\n"
        f"Do not edit files in this folder. Edit the source and re-run "
        f"`python tools/gather.py`.\n"
    )


# ---------- planning ----------


def is_skipped(path: Path) -> bool:
    if path.name in SKIP_FILENAMES:
        return True
    if any(part in SKIP_DIR_PARTS for part in path.relative_to(AGENTS_DIR).parts):
        return True
    return False


def plan_top_level() -> list[Stub]:
    plans = []
    for target, label in [
        (CLAUDE_DIR / "CLAUDE.md", ".claude/"),
        (GITHUB_DIR / "copilot-instructions.md", ".github/"),
        (GITHUB_DIR / "AGENTS.md", ".github/"),
    ]:
        plans.append(Stub(target, gen_top_level_instructions(target, label)))
    return plans


def plan_commands() -> list[Stub]:
    plans: list[Stub] = []
    commands_root = AGENTS_DIR / "commands"
    for source in sorted(commands_root.rglob("*.md")):
        if is_skipped(source):
            continue
        for target_dir, ext in [
            (CLAUDE_DIR / "commands", ".md"),
            (GITHUB_DIR / "prompts", ".prompt.md"),
        ]:
            target = target_dir / (source.stem + ext)
            plans.append(Stub(target, gen_command_stub(source, target)))
    return plans


def plan_skills() -> list[Stub]:
    plans: list[Stub] = []
    skills_root = AGENTS_DIR / "skills"
    for entry in sorted(skills_root.iterdir()):
        if entry.name in SKIP_FILENAMES:
            continue
        if entry.is_dir():
            skill_file = entry / "SKILL.md"
            if not skill_file.exists():
                continue
            text = skill_file.read_text()
            fields, body = parse_frontmatter(text)
            name = fields.get("name", entry.name)
            description = fields.get("description") or first_h1(body) or ""
            source = skill_file
        elif entry.is_file() and entry.suffix == ".md":
            text = entry.read_text()
            fields, body = parse_frontmatter(text)
            name = fields.get("name", entry.stem)
            description = fields.get("description") or first_h1(body) or ""
            source = entry
        else:
            continue
        for target_dir in [CLAUDE_DIR / "skills", GITHUB_DIR / "skills"]:
            target = target_dir / name / "SKILL.md"
            plans.append(Stub(target, gen_skill_stub(source, target, name, description)))
    return plans


def plan_folder_readmes() -> list[Stub]:
    plans: list[Stub] = []
    for target, source_dir, label in [
        (CLAUDE_DIR / "commands" / "README.md", AGENTS_DIR / "commands", "Claude Code"),
        (CLAUDE_DIR / "skills" / "README.md", AGENTS_DIR / "skills", "Claude Code"),
        (GITHUB_DIR / "prompts" / "README.md", AGENTS_DIR / "commands", "GitHub Copilot"),
        (GITHUB_DIR / "skills" / "README.md", AGENTS_DIR / "skills", "GitHub Copilot"),
    ]:
        plans.append(Stub(target, gen_folder_readme(target, source_dir, label)))
    return plans


def filter_surface(plans: list[Stub], surface: str) -> list[Stub]:
    if surface == "both":
        return plans
    root = CLAUDE_DIR if surface == "claude" else GITHUB_DIR
    return [p for p in plans if root in p.target.parents]


# ---------- orphan detection ----------


def find_orphans(planned_targets: set[Path], surfaces: list[Path]) -> list[Path]:
    orphans: list[Path] = []
    for surface in surfaces:
        if not surface.exists():
            continue
        for path in surface.rglob("*"):
            if not path.is_file():
                continue
            if path in planned_targets:
                continue
            try:
                text = path.read_text()
            except UnicodeDecodeError:
                continue
            if GENERATED_MARKER in text:
                orphans.append(path)
    return orphans


# ---------- main ----------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if stubs are out of date")
    parser.add_argument("--surface", choices=["claude", "github", "both"], default="both")
    args = parser.parse_args()

    if not AGENTS_DIR.is_dir():
        print(f"error: {AGENTS_DIR} does not exist", file=sys.stderr)
        return 1

    plans = (
        plan_top_level()
        + plan_folder_readmes()
        + plan_commands()
        + plan_skills()
    )
    plans = filter_surface(plans, args.surface)
    planned_targets = {p.target for p in plans}

    surfaces = []
    if args.surface in ("claude", "both"):
        surfaces.append(CLAUDE_DIR)
    if args.surface in ("github", "both"):
        surfaces.append(GITHUB_DIR)
    orphans = find_orphans(planned_targets, surfaces)

    drift: list[Stub] = []
    for plan in plans:
        existing = plan.target.read_text() if plan.target.exists() else None
        if existing != plan.content:
            drift.append(plan)

    if args.check:
        for plan in drift:
            rel = plan.target.relative_to(REPO_ROOT)
            kind = "create" if not plan.target.exists() else "update"
            print(f"{kind}: {rel}")
        for orphan in orphans:
            print(f"orphan: {orphan.relative_to(REPO_ROOT)}")
        if drift or orphans:
            print(
                f"\n{len(drift)} stub(s) out of date, {len(orphans)} orphan(s). "
                f"Run without --check to apply.",
                file=sys.stderr,
            )
            return 1
        print("All stubs in sync.")
        return 0

    for plan in plans:
        plan.target.parent.mkdir(parents=True, exist_ok=True)
        plan.target.write_text(plan.content)
    for orphan in orphans:
        orphan.unlink()
        print(f"removed orphan: {orphan.relative_to(REPO_ROOT)}")
    print(f"wrote {len(plans)} stub(s); {len(drift)} changed; {len(orphans)} orphan(s) removed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
